on: [push, pull_request]

name: CICD

env:
  WORKERS: 4
  BEE_VERSION: '1.7.0'
  BLOCKCHAIN_VERSION: '1.2.0'
  BEE_ENV_PREFIX: 'bee-factory'
  BEE_IMAGE_PREFIX: 'ethersphere'
  COMMIT_VERSION_TAG: 'false'
  BEE_API_URL: 'http://127.0.0.1:1633'
  BEE_DEBUG_API_URL: 'http://127.0.0.1:1635'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true
      
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --all --all-features -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      
      - uses: actions-rs/cargo@v1
        with:
          command: build
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Start Bee Factory environment
        run: |
          git clone --depth=1 https://github.com/fairDataSociety/bee-factory.git
          chmod +x -R ./bee-factory/scripts
          ./bee-factory/scripts/environment.sh start --detach --workers=$WORKERS

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      # Note that `actions-rs/grcov` Action can install `grcov` too,
      # but can't use faster installation methods yet.
      # As a temporary experiment `actions-rs/install` Action plugged in here.
      # Consider **NOT** to copy that into your workflow,
      # but use `actions-rs/grcov` only
      - name: Pre-installing grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov
          use-tool-cache: true

      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@v0.1
        with:
          coveralls-token: ${{ secrets.COVERALLS_TOKEN }}

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ${{ steps.coverage.outputs.report }}
  grcov_finalize:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Coveralls finalization
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
